# Generated by Django 4.2.7 on 2023-11-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dairy_dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('tot_land_area', models.FloatField()),
                ('num_cows', models.IntegerField()),
                ('price', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
