# Generated by Django 4.2.5 on 2023-11-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_user_ac_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_ac',
            old_name='passworld',
            new_name='password',
        ),
    ]
